image: Visual Studio 2017
environment:
  nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g node-gyp

after_build:
  - C:\projects\nodert\src\NodeRTCmd\bin\Debug\NodeRTCmd.exe --winmd "c:\Program Files (x86)\Windows Kits\10\UnionMetadata\Windows.winmd" --outdir c:\projects\nodert\out --verbose
